#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

var=0

while [ $var -lt 10 ];
do
	echo "Best School"
	((var++))
	if [ $var == 9 ];
	then
		echo "Hi"
	fi
done
