#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
var="Best School"
count=1
while (( count <= 10 ));
do
	echo "$var"
	if (( count == 9 ));then
		echo "Hi"
	fi
	(( count++ ))
done
