#!/usr/bin/env bash
# display numbers from 1 to 20.

var=1

while [ $var -le 20 ];
do
	
	case $var in
		5)
			echo "bad luck from China";;
		10)
			echo "bad luck from Japan";;
		18)
			echo "bad luck from Italy";;
	esac

	echo "$var"
	((var++))
done
