#!/usr/bin/env bash
# Install and configure ufw firewall

sudo apt update

# install ufw
sudo apt install ufw

# block incoming connections and allow outgoing
sudo ufw default allow outgoing
sudo ufw default deny incoming

# open required ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Turn on firewall
sudo ufw enable

# check status
sudo ufw status
