#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server
cp /etc/hosts /etc/hosts.new
echo "127.0.0.2	localhost" > /etc/hosts.new
echo "8.8.8.8	facebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
